sudo: required
dist: trusty
language: node_js
node_js:
  - '6'

env:
  - BUILD_DIR=lib
  - BUILD_DIR=demo

before_script:
  - cd $BUILD_DIR
  - npm install

script:
  - cd $BUILD_DIR
  - npm run build